/**
 * Type Action For Address
 */
export const SHOW_LIST_ADDRESS = 'SHOW_LIST_ADDRESS';
export const FETCH_DATA_ADDRESS_SUCCESS = 'FETCH_DATA_ADDRESS_SUCCESS';
export const FETCH_DATA_ADDRESS_REQUEST = 'FETCH_DATA_ADDRESS_REQUEST';
export const FETCH_DATA_ADDRESS_FAILED = 'FETCH_DATA_ADDRESS_FAILED';

export const ADD_DATA_ADDRESS_SUCCESS = 'ADD_DATA_ADDRESS_SUCCESS';
export const ADD_DATA_ADDRESS_REQUEST = 'ADD_DATA_ADDRESS_REQUEST';
export const ADD_DATA_ADDRESS_FAILED = 'ADD_DATA_ADDRESS_FAILED';

export const EDIT_DATA_ADDRESS_SUCCESS = 'EDIT_DATA_ADDRESS_SUCCESS';
export const EDIT_DATA_ADDRESS_REQUEST = 'EDIT_DATA_ADDRESS_REQUEST';
export const EDIT_DATA_ADDRESS_FAILED = 'EDIT_DATA_ADDRESS_FAILED';


export const ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS';
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const EXPORT_FILE_CSV = 'EXPORT_FILE_CSV';



